ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = 1
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.if-return]
[rule.increment-decrement]
[rule.var-declaration]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.indent-error-flow]
[rule.errorf]
[rule.superfluous-else]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.defer]
    arguments=[["call-chain","loop","method-call","return"]]
[rule.datarace]
[rule.time-equal]
[rule.unhandled-error]
    severity = "error"
    Exclude = ["pkg/datasets/**"]
    arguments = ["fmt.Print","fmt.Printf", "fmt.Println", "strings.Builder.WriteString", "io.WriteString", "strings.Builder.WriteRune"]
[rule.unused-parameter]
    severity = "error"
    Exclude = ["**/mocks/**"] 
